info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

# server config
server:
  port: 2221
  context-path:

# management config
management:
  context-path: /actuator
  security:
    enabled: false

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    metadata-map:
      management:
        context-path: ${server.context-path}${management.context-path}
    prefer-ip-address: true

# spring config
spring:
# boot-admin
  boot:
    admin:
      discovery:
        converter:
          management-context-pat‌​‌​h: ${server.context-path}${management.context-path}

# info config
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@
# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true

  cloud:
    config:
      name: @project.artifactId@
      server:
        git:
          uri: https://github.com/smile90/boot-frame-config
          search-paths: config-repo
          username:
          password:

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: SpringCloudConfig
    password: 123456