logging:
  level:
    root: info

info:
  version: @project.version@

# config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@

# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
  http:
    encoding:
      enabled: true
      charset: UTF-8

# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true

# 网关配置
zuul:
  ignored-services: '*'
  routes:
    boot-frame-auth:
      path: /auth/**
      serviceId: boot-frame-auth
    boot-frame-test:
      path: /test/**
      serviceId: boot-frame-test

    baidu:
      path: /baidu
      url: http://www.baidu.com